{{- $chartName := include "3d-ingestion-catalog.name" . -}}
{{- $tracingUrl := include "3d-ingestion-catalog.tracingUrl" . -}}
{{- $metricsUrl := include "3d-ingestion-catalog.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  DB_HOST: {{ quote .Values.db.host }}
  DB_PORT: {{ quote .Values.db.port }}
  DB_NAME: {{ .Values.db.database }}
  DB_CERT_PATH: /tmp/certs/{{ .Values.db.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ .Values.db.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ .Values.db.caFileName }}
  DB_ENABLE_SSL_AUTH: {{ .Values.db.sslEnable | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
{{- end }}
